export interface ProductReview {
  index : number;
  product_review_id: number;
  created_at: Date;
  customer_code: string;
  customer_name: string;
  product_id: string;
  product_subcategory_id: string;
  product_name: string;
  product_name_kana: string;
  product_code: string;
  product_title: string;
  bikou: string;
  product_desc: string;
  user_search_tag: string;
  product_search_tag: string;
  product_status: number;
  discount: number;
  subscribe_factor: number;
  safe_stock_amt: number;
  price: number;
  tax: number;
  min_sell_amt: number;
  max_sell_amt: number;
  product_created_at: string;
  image_url: string;
  title: string;
  review: string;
  rank: number;
  approver_id: number;
  approver_name: string;
}