export const ERROR_MESSAGE = {
  REQUIRED_EMAIL: "メールアドレスは必須です・",
  REQUIRED_PASSWORD: "パスワードは必須です・",
  REQUIRED_CONFIRM_PASSWORD: "パスワード（確認用）は必須です・",
  PASSWORDS_DO_NOT_MATCH: "パスワードが一致しません・",
  INVALID_EMAIL: "無効なメールアドレスです・",
  INVALID_PASSWORD: "無効なパスワードです・",
  ALL_FIELDS_REQUIRED: "すべての項目を入力してください・",
  PLEASE_SELECT_A_VALID_OPTION: "有効なオプションを選択してください・",
  INVALID_PHOTO: "無効な写真です・",
  INVALID_STARTING: "開業希望日は必須です・",
  INVALID_PREFECTURE: "都道府県は必須です・",
  INVALID_COMPANY_DESCRIPTION: "会社説明は必須です・",
  INVALID_COMPANY_NAME: "会社名は必須です・",
  INVALID_BUDGET: "予算は必須です・",
  INVALID_JOB_NAME: "無効な仕事名です・",
  INVALID_TIME: "無効な時間です・",
  INVALID_JOB_DESCRIPTION: "仕事の説明は必須です・",
  INVALID_CHAIRMAN: "会社の代表者は必須です・",
  INVALID_PHONE_NUMBER: "無効な電話番号です・",
  INVALID_LINK: "無効なリンクです・",
  INVALID_AREA: "無効なエリアです・",
  
};
