import { User } from "@/models/dataModel";

export const userList: Array<User> = [
  {
    userId: 1,
    userCode: "#12345678",
    userName: "山田",
    userNameKana: "ヤマダ",
    authority: "管理者",
    mailAddress: "test@gmail.com",
    phoneNumber: "090-1234-5678",
    status: 0,
  },
  {
    userId: 2,
    userCode: "#12345678",
    userName: "鈴木",
    userNameKana: "スズキ",
    authority: "システム管理者",
    mailAddress: "test@gmail.com",
    phoneNumber: "090-1234-5678",
    status: 1,
  },
  {
    userId: 3,
    userCode: "#12345678",
    userName: "川村",
    userNameKana: "カワムラ",
    authority: "管理者",
    mailAddress: "test@gmail.com",
    phoneNumber: "090-1234-5678",
    status: 1,
  },
  {
    userId: 4,
    userCode: "#12345678",
    userName: "山田",
    userNameKana: "ヤマダ",
    authority: "管理者",
    mailAddress: "test@gmail.com",
    phoneNumber: "090-1234-5678",
    status: 1,
  },
  {
    userId: 5,
    userCode: "#12345678",
    userName: "山田",
    userNameKana: "ヤマダ",
    authority: "管理者",
    mailAddress: "test@gmail.com",
    phoneNumber: "090-1234-5678",
    status: 0,
  },
];
