/**
 * This function is used to get the room ID by combining two user IDs
 * @author PSK
 * @param userId1 - The first user ID
 * @param userId2 - The second user ID
 * @returns The room ID generated by combining the two user IDs
 */
export const getRoomId = (userId1: any, userId2: any) => {
  const sortedIds = [userId1, userId2].sort();
  const roomId = sortedIds.join("-");
  return roomId;
};
