export enum QueryKey {
  APPLICANTS = "applicants",
  APPLICANT_DETAIL = "applicantDetail",
  JOBS = "jobs",
  JOB_TYPES = "jobTypes",
  USERS = "users",
  EVENTS = "events",
  LANGUAGES = "languages",
  CITY = "city",
  PROFILE = "profile",
  JOB_DETAILS = "jobDetails",
  MATCHED = "matched",
  MATCHED_DETAIL = "matchedDetail",
  FORGOT_PASSWORD = "forgotPassword",
  DASHBOARD = "dashboard",
  INTERVIEW = "interview",
  UPCOMING_INTERVIEW = "upcomingInterview",
  PRIVACY_POLICY = "privacyPolicy",
  NOTIFICATION = "notification",
  USER_INTERVIEW = "userInterview",
}
